### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by kagoya**

### CODE REVIEW

**Comment by timothyylim** [comment]
Hi @kagoya , thank you for the translation :) 
We are testing out a new translation service called crowdin. Would you be open to submitting your translation there as well? 

https://crowdin.com/project/h5p-advanced-text

It provides a fairly good GUI and hopefully will make it easier for future translators.

**Comment by kagoya** [comment]
Yes, I will try it.

**Comment by timothyylim** [comment]
Great stuff 👍  
Did you find it easy to use?

**Comment by kagoya** [comment]
I have tried crowdin. It is good and very easy to use.

**Comment by timothyylim** [comment]
Thank you @kagoya. I will close this pull request and merge your crowdin translation instead. 
If you would like to create any new translations in other repositories, just create an issue and I will set up crowdin for it :)

**Pull request closed without merging**
